language: csharp
sudo: required
dist: trusty
mono:
  - latest
os:
  - linux
  - osx
addons:  
  apt:
    packages:
    - libunwind8
osx_image: xcode7.1
services:
  - redis-server
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install icu4c; fi
env:
  - KOREBUILD_TEST_DNXCORE=false
script:
  - chmod a+x ./build.sh
  - ./build.sh
 