language: csharp
sudo: required
dist: trusty
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
mono:
  - 4.0.5
osx_image: xcode7.1
services:
  - redis-server
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install icu4c; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
env:
  - KOREBUILD_TEST_SKIPMONO=1
script:
  - chmod a+x ./build.sh
  - ./build.sh --quiet verify
 