name: '$(Date:yyyyMMdd)$(Rev:.r)'

trigger:
- dev
- master

pr:
  autoCancel: false
  branches:
    include:
    - '*'

# pool:
#   vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  ${{ if not(eq(variables['Build.SourceBranch'], 'refs/heads/master')) }}:
    versionSuffix: 'beta-$(Build.BuildNumber)'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    versionSuffix: ''

jobs:
- job: Windows
  displayName: 'Build & Test'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      projects: |
        CacheManager.sln
      arguments: '-c Release'
    name: 'Build'    
  - task: DotNetCoreCLI@2
    displayName: "dotnet test"
    inputs:
      command: 'test'
      projects: 'test/**/*.csproj'
      publishTestResults: true      
      arguments: '-c Release --no-build --no-restore --filter Category!=Unreliable'
  - script: 'dotnet pack src\DnsClient\DnsClient.csproj -c Release --no-build --no-restore --version-suffix "$(versionSuffix)" -v normal -o $(Build.ArtifactStagingDirectory)'
    name: 'Pack'
    displayName: 'dotnet pack'
  - task: PublishBuildArtifacts@1
    displayName: 'publish'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'cachemanager'
