name: '$(Date:yyyyMMdd)$(Rev:.r)'

trigger:
- dev
- master

pr:
  autoCancel: false
  branches:
    include:
    - '*'

# pool:
#   vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  ${{ if not(eq(variables['Build.SourceBranch'], 'refs/heads/master')) }}:
    versionSuffix: 'beta-$(Build.BuildNumber)'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    versionSuffix: ''

jobs:
- job: Windows
  displayName: 'Build & Test'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      projects: |
        CacheManager.sln
      arguments: '-c Release'
    name: 'Build'    
  - task: DotNetCoreCLI@2
    displayName: "dotnet test"
    inputs:
      command: 'test'
      projects: 'test/**/*.csproj'
      publishTestResults: true      
      arguments: '-c Release --no-build --no-restore --filter category!=Unreliable'
  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: 'pack'
      configuration: Release
      projects: 'CacheManager.sln'   
      packagesToPack: 'src/**/*.csproj'
      nobuild: true
      verbosityPack: normal
      outputDir: $(Build.ArtifactStagingDirectory)'
      arguments: 'CacheManager.sln --version-suffix "$(versionSuffix)"'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'cachemanager'
