name: '$(Date:yyyyMMdd)$(Rev:.r)'

trigger:
- dev
- master

pr:
  autoCancel: false
  branches:
    include:
    - '*'

# pool:
#   vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  ${{ if not(eq(variables['Build.SourceBranch'], 'refs/heads/master')) }}:
    versionSuffix: 'beta-$(Build.BuildNumber)'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    versionSuffix: ''

jobs:
- job: Windows
  displayName: 'Build & Test'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      projects: |
        CacheManager.sln
      arguments: '-c Release'
    name: 'Build'    
  - task: DotNetCoreCLI@2
    displayName: "dotnet test"
    inputs:
      command: 'test'
      projects: 'test/**/*.csproj'
      publishTestResults: true      
      arguments: '-c Release --no-build --no-restore --filter category!=Unreliable'
  - script: 'dotnet pack src\CacheManager.Core\CacheManager.Core.csproj -c Release --no-build --no-restore --version-suffix "$(versionSuffix)" -v normal -o $(Build.ArtifactStagingDirectory)'
    displayName: 'dotnet pack Core'
  - script: 'dotnet pack src\CacheManager.Microsoft.Extensions.Caching.Memory\CacheManager.Microsoft.Extensions.Caching.Memory.csproj -c Release --no-build --no-restore --version-suffix "$(versionSuffix)" -v normal -o $(Build.ArtifactStagingDirectory)'
    displayName: 'dotnet pack CacheManager.Microsoft.Extensions.Caching.Memory'
  - script: 'dotnet pack src\CacheManager.Microsoft.Extensions.Configuration\CacheManager.Microsoft.Extensions.Configuration.csproj -c Release --no-build --no-restore --version-suffix "$(versionSuffix)" -v normal -o $(Build.ArtifactStagingDirectory)'
    displayName: 'dotnet pack CacheManager.Microsoft.Extensions.Configuration'
  - script: 'dotnet pack src\CacheManager.Serialization.Bond\CacheManager.Serialization.Bond.csproj -c Release --no-build --no-restore --version-suffix "$(versionSuffix)" -v normal -o $(Build.ArtifactStagingDirectory)'
    displayName: 'dotnet pack CacheManager.Serialization.Bond'
  - script: 'dotnet pack src\CacheManager.Serialization.DataContract\CacheManager.Serialization.DataContract.csproj -c Release --no-build --no-restore --version-suffix "$(versionSuffix)" -v normal -o $(Build.ArtifactStagingDirectory)'
    displayName: 'dotnet pack CacheManager.Serialization.DataContract'
  - script: 'dotnet pack src\CacheManager.Serialization.Json\CacheManager.Serialization.Json.csproj -c Release --no-build --no-restore --version-suffix "$(versionSuffix)" -v normal -o $(Build.ArtifactStagingDirectory)'
    displayName: 'dotnet pack CacheManager.Serialization.Json'
  - script: 'dotnet pack src\CacheManager.Serialization.ProtoBuf\CacheManager.Serialization.ProtoBuf.csproj -c Release --no-build --no-restore --version-suffix "$(versionSuffix)" -v normal -o $(Build.ArtifactStagingDirectory)'
    displayName: 'dotnet pack CacheManager.Serialization.ProtoBuf'
  - script: 'dotnet pack src\CacheManager.StackExchange.Redis\CacheManager.StackExchange.Redis.csproj -c Release --no-build --no-restore --version-suffix "$(versionSuffix)" -v normal -o $(Build.ArtifactStagingDirectory)'
    displayName: 'dotnet pack CacheManager.StackExchange.Redis'
  - script: 'dotnet pack src\CacheManager.SystemRuntimeCaching\CacheManager.SystemRuntimeCaching.csproj -c Release --no-build --no-restore --version-suffix "$(versionSuffix)" -v normal -o $(Build.ArtifactStagingDirectory)'
    displayName: 'dotnet pack CacheManager.SystemRuntimeCaching'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'cachemanager'
